### PR TITLE
Some more translation for german

### PR DESCRIPTION
**Pull request by prsnbrg**
I can't find the missing translation on transifex.

I will add more translations in future.

### CODE REVIEW

**Comment by gino0631** [comment]
Thanks, we are working on integration with Transifex.

**Comment by prsnbrg** [comment]
Can you notify me, if Transifex translation is working?

**Comment by gino0631** [comment]
@prsnbrg OK.

**Comment by gino0631** [comment]
@prsnbrg it is already possible to submit [translations of the app on Transifex](https://www.transifex.com/nextcloud/nextcloud/metadata/) (though they are not getting into this repo yet, as we are discussing in nextcloud/docker-ci#166).

**Pull request closed without merging**
